import { TechId } from '../../src/core/types.ts';
import type { SimProfile } from './types.ts';

const BALANCED_PRIORITY: TechId[] = [
  TechId.CheaperRoads,
  TechId.FasterTrucks,
  TechId.LargerStations,
  TechId.Railway,
  TechId.DoubleCapacity,
  TechId.ExpressTrucks,
  TechId.BulkTerminals,
  TechId.Maritime,
  TechId.Aviation,
  TechId.EfficientRoutes,
  TechId.MassTransit,
  TechId.AdvancedAviation,
  TechId.DeepSea,
  TechId.AutoLoader,
  TechId.NightFreight,
  TechId.GlobalLogistics,
  TechId.SupplyChainAI,
];

const FRUGAL_PRIORITY: TechId[] = [
  TechId.CheaperRoads,
  TechId.FuelEfficiency,
  TechId.LargerStations,
  TechId.MaintenanceDept,
  TechId.BulkNetwork,
  TechId.DirectDelivery,
  TechId.Railway,
  TechId.BulkTerminals,
  TechId.NightFreight,
  TechId.BulkDiscount,
  TechId.Maritime,
  TechId.DeepSea,
  TechId.CargoNetwork,
  TechId.SupplyChainAI,
];

const AGGRESSIVE_PRIORITY: TechId[] = [
  TechId.FasterTrucks,
  TechId.CheaperRoads,
  TechId.ExpressTrucks,
  TechId.DoubleCapacity,
  TechId.Railway,
  TechId.EfficientRoutes,
  TechId.Aviation,
  TechId.AdvancedAviation,
  TechId.MassTransit,
  TechId.GreenRoutes,
  TechId.Maritime,
  TechId.DeepSea,
  TechId.AutoLoader,
  TechId.FossilSurge,
  TechId.GlobalLogistics,
  TechId.SupplyChainAI,
];

const MULTIMODAL_PRIORITY: TechId[] = [
  TechId.CheaperRoads,
  TechId.FasterTrucks,
  TechId.Railway,
  TechId.Aviation,
  TechId.Maritime,
  TechId.LargerStations,
  TechId.ExpressLine,
  TechId.FreightYard,
  TechId.AdvancedAviation,
  TechId.DeepSea,
  TechId.MassTransit,
  TechId.AutoLoader,
  TechId.GlobalLogistics,
  TechId.SupplyChainAI,
];

const AIR_CARGO_PRIORITY: TechId[] = [
  TechId.CheaperRoads,
  TechId.FasterTrucks,
  TechId.Aviation,
  TechId.LargerStations,
  TechId.AdvancedAviation,
  TechId.MassTransit,
  TechId.NightFreight,
  TechId.PassengerPlus,
  TechId.HeavyLift,
  TechId.RapidCargo,
  TechId.GlobalLogistics,
];

const SEA_CARGO_PRIORITY: TechId[] = [
  TechId.CheaperRoads,
  TechId.Bridging,
  TechId.Maritime,
  TechId.LargerStations,
  TechId.DeepSea,
  TechId.BulkNetwork,
  TechId.DirectDelivery,
  TechId.BulkDiscount,
  TechId.CargoNetwork,
  TechId.GlobalLogistics,
];

const LAND_ONLY_PRIORITY: TechId[] = [
  TechId.CheaperRoads,
  TechId.FasterTrucks,
  TechId.LargerStations,
  TechId.Railway,
  TechId.ExpressTrucks,
  TechId.DoubleCapacity,
  TechId.BulkTerminals,
  TechId.MassTransit,
  TechId.ExpressLine,
  TechId.FreightYard,
  TechId.EfficientRoutes,
  TechId.GreenRoutes,
  TechId.AutoLoader,
  TechId.MaglevRail,
  TechId.HyperCargo,
  TechId.SupplyChainAI,
];

const ALL_ROUTES_PRIORITY: TechId[] = [
  TechId.CheaperRoads,
  TechId.FasterTrucks,
  TechId.LargerStations,
  TechId.Railway,
  TechId.Aviation,
  TechId.Maritime,
  TechId.ExpressTrucks,
  TechId.DoubleCapacity,
  TechId.BulkTerminals,
  TechId.AdvancedAviation,
  TechId.DeepSea,
  TechId.ExpressLine,
  TechId.FreightYard,
  TechId.GlobalLogistics,
  TechId.SupplyChainAI,
];

export const SIM_PROFILES: SimProfile[] = [
  {
    id: 'balanced',
    name: 'Balanced Dispatcher',
    description: 'Builds steadily, keeps some cash in reserve, and prefers reliable truck upgrades.',
    techPriority: BALANCED_PRIORITY,
    thinkInterval: 10,
    routeTruckCap: 3,
    reserveBase: 25_000,
    reserveForExpansion: 55_000,
    hesitationChance: 0.08,
    techDelayChance: 0.18,
    candidatePool: 3,
    roadCostWeight: 0.85,
    railAffinity: 0.7,
    airAffinity: 0.55,
    seaAffinity: 0.45,
    railDistanceThreshold: 26,
    airDistanceThreshold: 48,
    seaDistanceThreshold: 42,
    modalRouteCap: 2,
  },
  {
    id: 'frugal',
    name: 'Frugal Planner',
    description: 'Buys cheaper infrastructure first and delays extra trucks until routes pay for themselves.',
    techPriority: FRUGAL_PRIORITY,
    thinkInterval: 12,
    routeTruckCap: 2,
    reserveBase: 40_000,
    reserveForExpansion: 70_000,
    hesitationChance: 0.14,
    techDelayChance: 0.28,
    candidatePool: 2,
    roadCostWeight: 1.15,
    railAffinity: 0.8,
    airAffinity: 0.25,
    seaAffinity: 0.6,
    railDistanceThreshold: 22,
    airDistanceThreshold: 60,
    seaDistanceThreshold: 34,
    modalRouteCap: 2,
  },
  {
    id: 'aggressive',
    name: 'Aggressive Operator',
    description: 'Expands fast, pushes truck counts harder, and accepts tighter cash buffers.',
    techPriority: AGGRESSIVE_PRIORITY,
    thinkInterval: 8,
    routeTruckCap: 4,
    reserveBase: 12_000,
    reserveForExpansion: 35_000,
    hesitationChance: 0.04,
    techDelayChance: 0.08,
    candidatePool: 4,
    roadCostWeight: 0.65,
    railAffinity: 0.45,
    airAffinity: 0.8,
    seaAffinity: 0.55,
    railDistanceThreshold: 30,
    airDistanceThreshold: 38,
    seaDistanceThreshold: 46,
    modalRouteCap: 3,
  },
  {
    id: 'multimodal',
    name: 'Multimodal Planner',
    description: 'Pushes into rail, air, and sea on purpose to stress-test late-game transfer chains.',
    techPriority: MULTIMODAL_PRIORITY,
    thinkInterval: 8,
    routeTruckCap: 2,
    reserveBase: 18_000,
    reserveForExpansion: 42_000,
    hesitationChance: 0.03,
    techDelayChance: 0.06,
    candidatePool: 4,
    roadCostWeight: 0.75,
    railAffinity: 0.95,
    airAffinity: 0.95,
    seaAffinity: 0.9,
    railDistanceThreshold: 18,
    airDistanceThreshold: 28,
    seaDistanceThreshold: 24,
    modalRouteCap: 3,
  },
  {
    id: 'aircargo',
    name: 'Air Cargo Planner',
    description: 'Rushes airports and advanced aviation to test long-haul air balance and hub feeders.',
    techPriority: AIR_CARGO_PRIORITY,
    thinkInterval: 8,
    routeTruckCap: 2,
    reserveBase: 14_000,
    reserveForExpansion: 30_000,
    hesitationChance: 0.02,
    techDelayChance: 0.05,
    candidatePool: 4,
    roadCostWeight: 0.7,
    railAffinity: 0.1,
    airAffinity: 1,
    seaAffinity: 0.1,
    railDistanceThreshold: 999,
    airDistanceThreshold: 18,
    seaDistanceThreshold: 999,
    modalRouteCap: 3,
  },
  {
    id: 'seacargo',
    name: 'Sea Cargo Planner',
    description: 'Rushes ports and maritime tech to probe water logistics and coastal late-game routes.',
    techPriority: SEA_CARGO_PRIORITY,
    thinkInterval: 9,
    routeTruckCap: 2,
    reserveBase: 16_000,
    reserveForExpansion: 34_000,
    hesitationChance: 0.03,
    techDelayChance: 0.06,
    candidatePool: 4,
    roadCostWeight: 0.7,
    railAffinity: 0.1,
    airAffinity: 0.1,
    seaAffinity: 1,
    railDistanceThreshold: 999,
    airDistanceThreshold: 999,
    seaDistanceThreshold: 18,
    modalRouteCap: 3,
  },
  {
    id: 'landonly',
    name: 'Land-Only Late Game',
    description: 'Benchmarks late game without air or sea so rail and land scaling can be compared cleanly.',
    techPriority: LAND_ONLY_PRIORITY,
    thinkInterval: 8,
    routeTruckCap: 3,
    reserveBase: 20_000,
    reserveForExpansion: 48_000,
    hesitationChance: 0.04,
    techDelayChance: 0.08,
    candidatePool: 4,
    roadCostWeight: 0.8,
    railAffinity: 0.95,
    airAffinity: 0,
    seaAffinity: 0,
    railDistanceThreshold: 20,
    airDistanceThreshold: 999,
    seaDistanceThreshold: 999,
    modalRouteCap: 3,
  },
  {
    id: 'allroutes',
    name: 'All Routes Late Game',
    description: 'Allows rail, air, and sea together for direct late-game comparison against the land-only baseline.',
    techPriority: ALL_ROUTES_PRIORITY,
    thinkInterval: 8,
    routeTruckCap: 3,
    reserveBase: 20_000,
    reserveForExpansion: 48_000,
    hesitationChance: 0.04,
    techDelayChance: 0.08,
    candidatePool: 4,
    roadCostWeight: 0.78,
    railAffinity: 0.8,
    airAffinity: 0.75,
    seaAffinity: 0.75,
    railDistanceThreshold: 20,
    airDistanceThreshold: 26,
    seaDistanceThreshold: 24,
    modalRouteCap: 3,
  },
];

export function getProfiles(filter?: string): SimProfile[] {
  if (!filter || filter === 'all') return SIM_PROFILES;
  return SIM_PROFILES.filter((profile) => profile.id === filter);
}
